//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace C2BR.GestorEducacao.UI.GEDUC.F9000_CtrlResultados.F9220_IndicesEducacaoEnem {
    
    
    public partial class NotaMediaEscConEnsMed {
    }
}
